name: NmapAutomator Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  nmap-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker build action
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker login action
      uses: docker/login-action@v3

    - name: Create output directory
      run: mkdir -p auto_scans

    - name: Run nmapAutomator scan
      run: |
        docker run --rm \
        -v $(pwd)/auto_scans:/nmapAutomator/auto_scans \
        securitycompanion/nmapautomator \
        -t na -H 45.33.32.156 -t Full

    - name: Compare results
      run: |
        # Compare all output files with expected results
        for file in auto_scans/*; do
          echo "Checking content of file: $filename"
          filename=$(basename $file)
          if [ -f "expected_scans/$filename" ]; then
            diff -u "expected_scans/$filename" "$file" 
            # || exit 1
          else
            echo "⚠️ Missing expected file: $filename"
            # exit 1
          fi
        done
