name: nmapAutomatorNG Test

on: workflow_dispatch

jobs:
  nmap-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker build action
      uses: docker/setup-buildx-action@v3

    - name: Create output directory
      run: mkdir -p auto_scans

    - name: Run nmapAutomatorNG scan
      run: |
        docker run --rm \
        -v $(pwd)/auto_scans:/nmapAutomatorNG/auto_scans \
        securitycompanion/nmapAutomatorNG \
        -t na -H 45.33.32.156 -t Basic

    - name: Validate output files for expected words
      run: |
        # Define expected words
        declare -A expected_words=(
        ["scan1.txt"]="open|filtered|closed"
        ["scan2.txt"]="tcp|udp|service"
        )

        # Check each file for expected words
        for file in auto_scans/*; do
        print "check content of file $file"
        filename=$(basename "$file")
        print "$filename"
        if [[ ${expected_words[$filename]+_} ]]; then
            grep -E "${expected_words[$filename]}" "$file" > /dev/null || {
            echo "❌ Validation failed for $filename. Expected words not found."
            # exit 1
            }
            echo "✅ Validation passed for $filename."
        else
            echo "⚠️ No validation rules defined for $filename."
        fi
        done
